services:
  backup:
    image: vohoang/elasticsearch-snapshot-s3:latest
    environment:
      SCHEDULE: '0 0 1 * * ?'     # optional
      BACKUP_KEEP_DAYS: 7     # optional
      PASSPHRASE: passphrase  # optional
      S3_REGION: region
      S3_ACCESS_KEY_ID: key
      S3_SECRET_ACCESS_KEY: secret
      S3_BUCKET: my-bucket
      S3_PREFIX: backup
      ELASTICSEARCH_HOST: host:9200
      ELASTICSEARCH_USERNAME: user
      ELASTICSEARCH_PASSWORD: password
      ELASTICSEARCH_REPO_NAME: repo
      ELASTICSEARCH_INDEX_NAME: index-name
